#!/bin/bash

echo "🔐 Google OAuth Configuration Quick Reference"
echo "============================================="
echo ""
echo "📋 STEP-BY-STEP CHECKLIST:"
echo ""
echo "☐ 1. Google Cloud Console Setup"
echo "   • Visit: https://console.cloud.google.com/"
echo "   • Create/select project: 'MathTutor AI'"
echo "   • Enable APIs: Google+ API, People API"
echo "   • Configure OAuth consent screen"
echo "   • Create OAuth 2.0 credentials"
echo ""
echo "☐ 2. Get Your Supabase Project URL"
echo "   • Go to: https://app.supabase.com/"
echo "   • Copy your project URL: https://[PROJECT_ID].supabase.co"
echo ""
echo "☐ 3. Configure Redirect URIs in Google Cloud Console"
echo "   • JavaScript origins: http://localhost:5173"
echo "   • Redirect URIs:"
echo "     - https://[YOUR_PROJECT_ID].supabase.co/auth/v1/callback"
echo "     - http://localhost:5173/auth/callback"
echo ""
echo "☐ 4. Enable Google Provider in Supabase"
echo "   • Go to Authentication → Providers"
echo "   • Enable Google"
echo "   • Add Client ID and Client Secret from Google Cloud Console"
echo ""
echo "☐ 5. Configure Site URL in Supabase"
echo "   • Go to Authentication → URL Configuration"
echo "   • Site URL: http://localhost:5173"
echo "   • Redirect URLs (add each separately):"
echo "     - http://localhost:5173"
echo "     - http://localhost:5173/"
echo "     - http://localhost:5173/auth/callback"
echo ""
echo "🔍 CURRENT SUPABASE PROJECT INFO:"
echo "• Project URL format: https://[PROJECT_ID].supabase.co"
echo "• To find your Project ID:"
echo "  1. Go to https://app.supabase.com/"
echo "  2. Select your project"
echo "  3. Look at the URL or Settings → General"
echo ""
echo "⚠️  IMPORTANT NOTES:"
echo "• Keep Client Secret secure - never expose in frontend"
echo "• OAuth changes can take 5-10 minutes to propagate"
echo "• Test in incognito/private browsing mode"
echo "• Double-check all URLs exactly match (no trailing slashes)"
echo ""
echo "🧪 TESTING STEPS:"
echo "1. Start your app: npm run dev"
echo "2. Go to: http://localhost:5173"
echo "3. Click login → 'Continue with Google'"
echo "4. Should redirect to Google OAuth consent screen"
echo "5. After approval, should redirect back and log in"
echo ""
echo "🆘 COMMON ERRORS & SOLUTIONS:"
echo "• redirect_uri_mismatch → Check redirect URIs in Google Cloud Console"
echo "• unauthorized_client → Verify OAuth consent screen is configured"
echo "• access_denied → Check scopes and test user settings"
echo ""
echo "📖 FULL GUIDE: See GOOGLE_OAUTH_SETUP.md for detailed instructions"
echo ""
echo "✅ Ready to configure Google OAuth!"