#!/bin/bash

echo "🔧 OAuth Session Debugging Guide"
echo "=================================="
echo ""
echo "🧪 CURRENT ISSUE ANALYSIS:"
echo "• Auth service initializes but finds no session"
echo "• Duplicate initializations happening"
echo "• INITIAL_SESSION event shows null session"
echo ""
echo "📊 DEBUGGING STEPS:"
echo ""
echo "Step 1: Check Browser Storage"
echo "→ Open DevTools (F12) → Application → Storage"
echo "→ Look for 'supabase.auth.token' in localStorage"
echo "→ Look for session cookies"
echo ""
echo "Step 2: Test Google OAuth Flow"
echo "→ Clear browser data (Ctrl+Shift+Del)"
echo "→ Visit: http://localhost:5174"
echo "→ Open Console (F12) → Console"
echo "→ Click 'Continue with Google'"
echo "→ Watch console logs during redirect"
echo ""
echo "Step 3: Check Console Output"
echo "Expected logs:"
echo "✅ 'Initializing auth service...'"
echo "✅ 'Auth service initialized: {hasSession: true, hasUser: true}'"
echo "✅ 'Auth state changed: SIGNED_IN [email]'"
echo "✅ 'App: Auth state changed, user: [email]'"
echo ""
echo "❌ Current logs show:"
echo "• 'Auth service initialized: {hasSession: false, hasUser: false}'"
echo "• 'Auth state changed: INITIAL_SESSION undefined'"
echo ""
echo "🔍 TROUBLESHOOTING:"
echo ""
echo "If session not persisting:"
echo "1. Check browser settings:"
echo "   • Third-party cookies enabled"
echo "   • LocalStorage enabled"
echo "   • Not in strict privacy mode"
echo ""
echo "2. Clear all auth data:"
echo "   • localStorage.clear()"
echo "   • sessionStorage.clear()"
echo "   • Clear cookies for localhost"
echo ""
echo "3. Test in different browser:"
echo "   • Try Chrome/Firefox/Edge"
echo "   • Try normal vs incognito mode"
echo ""
echo "4. Check Supabase configuration:"
echo "   • Redirect URLs match exactly"
echo "   • Site URL is correct"
echo "   • Google OAuth provider enabled"
echo ""
echo "🎯 NEXT ACTIONS:"
echo "1. Test Google OAuth with console open"
echo "2. Check if session data is stored after login"
echo "3. Verify redirect happens correctly"
echo "4. Confirm user data reaches the app"
echo ""
echo "💡 If still failing, try manual session check:"
echo "   In console: supabase.auth.getSession()"