#!/bin/bash

echo "🔄 Vite Port Change - OAuth Update Required"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANT: Vite is now running on PORT 5174 (not 5173)"
echo ""
echo "🔧 UPDATE REQUIRED IN GOOGLE CLOUD CONSOLE:"
echo "1. Go to: https://console.cloud.google.com/"
echo "2. Select your project → APIs & Services → Credentials"
echo "3. Edit your OAuth 2.0 Client ID"
echo "4. Update Authorized JavaScript origins:"
echo "   • Add: http://localhost:5174"
echo "   • Keep: http://localhost:5173 (for future use)"
echo "5. Update Authorized redirect URIs:"
echo "   • Add: http://localhost:5174/auth/callback"
echo "   • Keep existing URLs"
echo ""
echo "🔧 UPDATE REQUIRED IN SUPABASE:"
echo "1. Go to: https://app.supabase.com/"
echo "2. Your project → Authentication → URL Configuration"
echo "3. Update Site URL to: http://localhost:5174"
echo "4. Add new Redirect URLs:"
echo "   • http://localhost:5174"
echo "   • http://localhost:5174/"
echo "   • http://localhost:5174/auth/callback"
echo "   • Keep existing 5173 URLs for backup"
echo ""
echo "🌐 NEW APPLICATION URL:"
echo "   http://localhost:5174"
echo ""
echo "✅ VITE STATUS:"
echo "• Dependencies re-optimized"
echo "• Cache cleared"
echo "• Server running on port 5174"
echo ""
echo "🎯 NEXT STEPS:"
echo "1. Update OAuth configurations (above)"
echo "2. Visit: http://localhost:5174"
echo "3. Test Google OAuth login"
echo ""
echo "💡 TO USE PORT 5173 AGAIN:"
echo "   Stop the server and run: npm run dev"
echo "   (Port 5173 might be available again)"