#!/bin/bash

echo "🔄 Port 5173 Configuration Update Guide"
echo "======================================="
echo ""
echo "✅ VITE SERVER NOW ON PORT 5173"
echo "   Application URL: http://localhost:5173"
echo ""
echo "🔧 REQUIRED OAUTH UPDATES:"
echo ""
echo "1️⃣ GOOGLE CLOUD CONSOLE:"
echo "   • Go to: https://console.cloud.google.com/"
echo "   • Select your project → APIs & Services → Credentials"
echo "   • Edit OAuth 2.0 Client ID"
echo "   • Update Authorized JavaScript origins:"
echo "     - REMOVE: http://localhost:5174"
echo "     - ENSURE: http://localhost:5173 is present"
echo "   • Update Authorized redirect URIs:"
echo "     - REMOVE: http://localhost:5174/auth/callback"
echo "     - ENSURE: http://localhost:5173/auth/callback is present"
echo ""
echo "2️⃣ SUPABASE CONFIGURATION:"
echo "   • Go to: https://app.supabase.com/"
echo "   • Your project → Authentication → URL Configuration"
echo "   • Update Site URL:"
echo "     - CHANGE TO: http://localhost:5173"
echo "   • Update Redirect URLs:"
echo "     - REMOVE: http://localhost:5174 entries"
echo "     - ENSURE these are present:"
echo "       • http://localhost:5173"
echo "       • http://localhost:5173/"
echo "       • http://localhost:5173/auth/callback"
echo ""
echo "📋 STEP-BY-STEP CHECKLIST:"
echo ""
echo "☐ 1. Update Google Cloud Console JavaScript origins"
echo "☐ 2. Update Google Cloud Console redirect URIs"
echo "☐ 3. Update Supabase Site URL to port 5173"
echo "☐ 4. Update Supabase Redirect URLs to port 5173"
echo "☐ 5. Clear browser cache and cookies"
echo "☐ 6. Test Google OAuth on http://localhost:5173"
echo ""
echo "🌐 NEW APPLICATION URL:"
echo "   http://localhost:5173"
echo ""
echo "🧪 TESTING AFTER UPDATES:"
echo "1. Visit: http://localhost:5173"
echo "2. Open Console (F12)"
echo "3. Run: window.testAuth.checkSession()"
echo "4. Click 'Continue with Google'"
echo "5. Complete OAuth authorization"
echo "6. Run: window.testAuth.checkSession() again"
echo ""
echo "⚠️  IMPORTANT:"
echo "• OAuth changes may take 5-10 minutes to propagate"
echo "• Clear browser data after making changes"
echo "• Test in incognito mode to avoid cache issues"
echo ""
echo "🎯 EXPECTED RESULT:"
echo "After OAuth: {hasUser: true, userEmail: 'your@email.com'}"
echo ""
echo "🚀 Ready to update OAuth configuration for port 5173!"