from manim import *

class MathSolutionScene(Scene):
    def construct(self):
        self.play(Write(Text("###").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("问题分析").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("题目要求我们求一个**三角形的面积**，已知这个三角形的**底边长度为8**，**高为6**。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("这是一个基础的几何问题，主要考察的是对**三角形面积公式**的理解和应用。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("###").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("详细解题步骤（每步都要解释原理）").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("**第一步：回忆三角形面积公式**").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("三角形的面积计算公式是：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("\text{面积} = \frac{1}{2} \times \text{底边长度} \times \text{高}").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("这个公式的来源是将两个相同的三角形拼成一个平行四边形，而平行四边形的面积是“底 × 高”，所以一个三角形就是它的一半。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("**第二步：代入已知数值**").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("题目中给出：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- 底边长度 = 8").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- 高 = 6").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("将这些值代入公式：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("\text{面积} = \frac{1}{2} \times 8 \times 6").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("**第三步：进行乘法运算**").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("先算乘法部分：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("8 \times 6 = 48").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("再乘以 $\frac{1}{2}$：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("\frac{1}{2} \times 48 = 24").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("###").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("最终答案").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("该三角形的面积是：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("\boxed{24}").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("单位如果是厘米，则面积单位是平方厘米（cm²）；如果是米，则是平方米（m²），依此类推。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("###").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("验证过程").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("我们可以反向验证一下结果是否合理：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- 如果一个底为8、高为6的三角形面积是24，那么根据公式：").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("\text{面积} = \frac{1}{2} \times 8 \times 6 = 24").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("$$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("这与我们的计算一致，说明结果正确。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("###").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("相关数学概念").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- **三角形面积公式**：$\text{面积} = \frac{1}{2} \times \text{底} \times \text{高}$").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- **底边**：三角形中任意一条边都可以作为底边。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- **高**：从底边对应的顶点垂直到底边的距离。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- **单位面积**：面积的单位是长度单位的平方（如 cm²、m² 等）。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- **几何图形的基本性质**：理解图形的构成和测量方法。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("###").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("常见错误提醒").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- ❌ 忘记乘以 $\frac{1}{2}$，直接用“底 × 高”得到48，这是错误的。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- ❌ 混淆“底”和“高”的定义，比如误把斜边当作高。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- ❌ 单位混淆，忘记面积单位是平方单位。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("- ❌ 计算过程中粗心出错，例如8×6算成42或40等。").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("---").scale(0.8)))
        self.wait(1)
        self.play(Write(Text("希望这个讲解能帮助你更好地理解和掌握三角形面积的计算！如果有更多类似的问题，欢迎继续提问哦 😊").scale(0.8)))
        self.wait(1)
