#!/bin/bash

echo "🚨 WSL2 Network Connection Completely Blocked"
echo "============================================="
echo ""
echo "🔍 ISSUE: All IP addresses refuse connection"
echo "This indicates WSL2 networking is not properly configured"
echo ""
echo "🔧 WINDOWS-SIDE FIXES REQUIRED:"
echo ""
echo "1️⃣ RESTART WSL2 (Run in Windows CMD/PowerShell):"
echo "   wsl --shutdown"
echo "   wsl"
echo ""
echo "2️⃣ RESET WSL2 NETWORKING (Windows PowerShell as Admin):"
echo "   wsl --shutdown"
echo "   netsh winsock reset"
echo "   netsh int ip reset"
echo "   wsl"
echo ""
echo "3️⃣ WINDOWS FIREWALL (Windows Settings):"
echo "   • Windows Security → Firewall & network protection"
echo "   • Allow an app through firewall"
echo "   • Add 'Node.js' and 'WSL' if not present"
echo "   • Enable for Private networks"
echo ""
echo "4️⃣ HYPER-V/WSL2 FEATURE CHECK (Windows PowerShell as Admin):"
echo "   dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart"
echo "   dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart"
echo ""
echo "5️⃣ ALTERNATIVE: FILE-BASED ACCESS"
echo "   • Open Windows File Explorer"
echo "   • Navigate to: \\\\wsl$\\Ubuntu\\mnt\\d\\AI\\VideoTutor\\dist"
echo "   • Double-click index.html"
echo ""
echo "6️⃣ USE WINDOWS-SIDE DEVELOPMENT:"
echo "   • Copy project to Windows (e.g., C:\\VideoTutor)"
echo "   • Run npm commands from Windows Command Prompt"
echo ""
echo "🎯 IMMEDIATE SOLUTIONS:"
echo ""
echo "Option A - File Access:"
echo "1. Open File Explorer"
echo "2. Address bar: \\\\wsl$\\Ubuntu\\mnt\\d\\AI\\VideoTutor\\dist"
echo "3. Double-click index.html"
echo ""
echo "Option B - Copy to Windows:"
echo "1. Copy entire VideoTutor folder to C:\\"
echo "2. Open Windows Command Prompt"
echo "3. cd C:\\VideoTutor"
echo "4. npm install"
echo "5. npm run dev"
echo ""
echo "🚀 The file-based access should work immediately!"
echo ""
echo "📁 Direct file path: \\\\wsl$\\Ubuntu\\mnt\\d\\AI\\VideoTutor\\dist\\index.html"