#!/bin/bash

echo "🔧 WSL2 Localhost Connection Fix"
echo "================================"
echo ""
echo "🔍 DIAGNOSIS:"
echo "Vite server is running but localhost:5173 shows 'connection refused'"
echo "This is a common WSL2 networking issue"
echo ""
echo "✅ SOLUTIONS TO TRY:"
echo ""
echo "1️⃣ USE WSL IP ADDRESS:"
echo "   • Try: http://172.26.198.29:5173/"
echo "   • Try: http://10.255.255.254:5173/"
echo ""
echo "2️⃣ WINDOWS FIREWALL FIX:"
echo "   • Open Windows Defender Firewall"
echo "   • Allow an app through firewall"
echo "   • Add 'Node.js' if not present"
echo "   • Enable for both Private and Public networks"
echo ""
echo "3️⃣ WSL2 PORT FORWARDING:"
echo "   Open PowerShell as Administrator and run:"
echo "   netsh interface portproxy add v4tov4 listenport=5173 listenaddress=0.0.0.0 connectport=5173 connectaddress=172.26.198.29"
echo ""
echo "4️⃣ ALTERNATIVE - ACCESS VIA FILE EXPLORER:"
echo "   • Open Windows File Explorer"
echo "   • Type in address bar: \\\\wsl$\\Ubuntu\\mnt\\d\\AI\\VideoTutor"
echo "   • Double-click index.html (if it exists)"
echo ""
echo "5️⃣ BUILD AND SERVE STATIC VERSION:"
echo "   • Run: npm run build"
echo "   • Run: npm run preview"
echo "   • Try accessing the preview URL"
echo ""
echo "🎯 IMMEDIATE TEST:"
echo "Try these URLs in your browser:"
echo "• http://172.26.198.29:5173/"
echo "• http://10.255.255.254:5173/"
echo ""
echo "🔧 IF STILL NOT WORKING:"
echo "1. Restart WSL: wsl --shutdown (in Windows CMD)"
echo "2. Restart Docker Desktop (if installed)"
echo "3. Try different port: npm run dev -- --port 3000"
echo ""
echo "💡 The WSL IP addresses should work immediately!"